name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          # Use the secret in your commands
          echo "Deploying with API Key: ${{ secrets.client_id }}"
        env:
          API_KEY: ${{ secrets.client_id }}
